<html>
<%@ page pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/jsp/dumbhippo.tld" prefix="dh" %>
<%@ taglib tagdir="/WEB-INF/tags/2" prefix="dht2" %>
<%@ taglib tagdir="/WEB-INF/tags/3" prefix="dht3" %>
<%@ taglib tagdir="/WEB-INF/tags/gnome" prefix="gnome" %>

<c:if test="${!signin.valid}">
	<%-- this is a bad error message but should never happen since we require signin to get here --%>
	<dht2:errorPage>Not signed in</dht2:errorPage>
</c:if>

<dht3:requirePersonBean beanClass="com.dumbhippo.web.pages.PersonPage"/>

<dh:bean id="account" class="com.dumbhippo.web.pages.AccountPage" scope="page"/>

<%-- This is a Facebook authetication token and an error message generated by us if we couldn't --%>
<%-- process the token. We use FacebookVerifyFromAccountServlet to process the token, which then redirects here. --%>
<jsp:setProperty name="account" property="facebookAuthToken" param="auth_token"/>
<jsp:setProperty name="account" property="facebookErrorMessage" param="error_message"/>

<head>
    <gnome:title><c:out value="${person.viewedPerson.name}"/>'s Account</gnome:title>
	<gnome:stylesheet name="site"/>
	<gnome:stylesheet name="account"/>	
	<gnome:faviconIncludes/>
	<dht3:accountJavascriptSetup account="${account}"/>
</head>
<body>
	<gnome:page>
		<dht3:accountStatus enableControl="true" includeDownload="false"/>
		<div id="gnomeAccountContents" class="${signin.active ? 'gnome-account-contents' : 'gnome-account-contents-disabled'}">
			<dht3:accountEditTable account="${account}" termsOfUseNote="${termsOfUseNote}"/>
		</div>
	</gnome:page>
	<dht2:photoChooser/>
</body>
</html>
