package com.dumbhippo.dm;

/**
 * ChangeNotifier represents a facility for sending out notifications
 * across all servers.
 *
 * Eventually timestamp management should be moved in here, replacing
 * the physical timestamp based DataModel.getTimestamp(); broadcastNotify() 
 * should return a timestamp for the message generated by the central queue 
 * daemon, and the timestamp for a ReadOnlySession should be the timestamp
 * of the last message sent or received by this node when the transaction
 * started.   
 * 
 * @author otaylor
 */
public interface ChangeNotifier {
	/**
	 * Send out a set of change notifications to all other servers in the cluster,
	 * not including the current server. {@link DataModel#doNotify(ChangeNotificationSetn)}
	 * should be called on each server.
	 * 
	 * @param notifications the notifications to send out
	 */
	void broadcastNotify(ChangeNotificationSet notifications);
}
