IMGDIR=..\..\common\images

all: *.png
	-mkdir $(OUTDIR)\images
	copy $(IMGDIR)\bar_middle.png $(OUTDIR)\images
	copy $(IMGDIR)\bar_pipe.png $(OUTDIR)\images
	copy $(IMGDIR)\bar_x2.png $(OUTDIR)\images
	copy $(IMGDIR)\bar_x.png $(OUTDIR)\images
	copy $(IMGDIR)\find.png $(OUTDIR)\images
	copy $(IMGDIR)\home2.png $(OUTDIR)\images
	copy $(IMGDIR)\home.png $(OUTDIR)\images
	copy $(IMGDIR)\hush2.png $(OUTDIR)\images
	copy $(IMGDIR)\hush.png $(OUTDIR)\images
	copy $(IMGDIR)\lid.png $(OUTDIR)\images
	copy $(IMGDIR)\mugshotstacker.png $(OUTDIR)\images
	copy $(IMGDIR)\photo_icon.png $(OUTDIR)\images
	copy $(IMGDIR)\search_x.png $(OUTDIR)\images
	copy $(IMGDIR)\unhush2.png $(OUTDIR)\images
	copy $(IMGDIR)\unhush.png $(OUTDIR)\images

clean:
	-deltree $(OUTDIR)\images
