import "oaidl.idl";
import "ocidl.idl";

#include "HippoDispID.h"

[
    uuid(39794B35-15C8-43b8-A1D7-AEB345E8355C), // LIBID_HippoExplorer
    helpstring("DumbHippo Explorer Interface"),
    lcid(0x0000),
    version(0.1)
]
library HippoExplorer {
    [
	uuid(82344E95-33D8-44e3-A2BF-2E4A0CCC6C95), // IID_IHippoEmbed
	helpstring("DumbHippo Embedded Object"),
	dual,
	oleautomation
    ]
    interface IHippoEmbed : IDispatch
    {
	[helpstring("Display message")]
	HRESULT DisplayMessage([in] BSTR message);
	[helpstring("Insert debugging information into the element")]
	HRESULT DebugDump([in] IDispatch *element);
	[helpstring("Close the browser window; usually used for server side dialogs")]
	HRESULT CloseWindow(void);
    }
    [
	uuid(48584F5A-B7EB-4eda-B058-42DEDB94A89E), // IID_IHippoEmbedEvents
	helpstring("DumbHippo Embedded Object Events"),
	dual,
	oleautomation
    ]
    interface IHippoEmbedEvents : IDispatch
    {
	[helpstring("Toplevel location changed")]
	[id(HIPPO_DISPID_LOCATIONCHANGED)] HRESULT LocationChanged(BSTR locationURL);
    }
    [
	uuid(5A96BF90-0D8A-4200-A23B-1C8DABC0CC04) // CLSID_HippoEmbed
    ]
    coclass HippoEmbed
    {
	[default] interface IHippoEmbed;
	[default, source] interface IHippoEmbedEvents;
    }
}
