#!/usr/bin/python
import os,sys

import gconf

from godmode import gnomepanel,odpanel

os.environ['OD_SESSION'] = "1"

panels = gnomepanel.get_toplevels()
if panels[0] != odpanel.PANEL_ID:
	odpanel.setup_panels()

os.execvp('gnome-session', ['gnome-session'])
sys.exit(1)