all: *.xml *.css *.png *.js
    -mkdir $(OUTDIR)\applets
    copy activeLeft.png $(OUTDIR)\applets
    copy activeRight.png $(OUTDIR)\applets
    copy bubble.css $(OUTDIR)\applets
    copy bubble.js $(OUTDIR)\applets
    copy bubbleList.css $(OUTDIR)\applets	
    copy bubbleList.js $(OUTDIR)\applets
    copy bubbleList.xml $(OUTDIR)\applets
    copy clientstyle.xml $(OUTDIR)\applets
    copy close.png $(OUTDIR)\applets
    copy dh.css $(OUTDIR)\applets	    
    copy dh.js $(OUTDIR)\applets
    copy clientstyle.xml $(OUTDIR)\applets
    copy flickr.js $(OUTDIR)\applets	
    copy flickrstatus.xml $(OUTDIR)\applets
    copy flickrstatus.js $(OUTDIR)\applets    
    copy groupChat.png $(OUTDIR)\applets
    copy menu.css $(OUTDIR)\applets	
    copy menu.js $(OUTDIR)\applets
    copy menu.xml $(OUTDIR)\applets
    copy notification.css $(OUTDIR)\applets	
    copy notification.js $(OUTDIR)\applets
    copy notification.xml $(OUTDIR)\applets

clean:
	-deltree $(OUTDIR)\applets
