all:
	-mkdir $(OUTDIR)
	copy charset.dll $(OUTDIR)
	copy iconv.dll $(OUTDIR)
	copy intl.dll $(OUTDIR)
	copy libglib-2.0-0.dll $(OUTDIR)
	copy libgthread-2.0-0.dll $(OUTDIR)
	copy libgobject-2.0-0.dll $(OUTDIR)

clean:
	del $(OUTDIR)\charset.dll
	del $(OUTDIR)\iconv.dll
	del $(OUTDIR)\intl.dll
	del $(OUTDIR)\libglib-2.0-0.dll
	del $(OUTDIR)\libgthread-2.0-0.dll
	del $(OUTDIR)\libgobject-2.0-0.dll


