#!/usr/bin/env python
import os,sys

import gnomedesktop

if not os.getenv('OD_SESSION'):
	sys.exit(0)

datadir_env = os.getenv('XDG_DATA_DIRS')
if datadir_env:
	datadirs = datadir_env.split(':')
else:
	datadirs = ['/usr/share/']
autostart_dirs = map(lambda x: os.path.join(x, 'online-desktop', 'autostart'), datadirs)
for dir in autostart_dirs:
	if os.access(dir, os.R_OK):
		for name in os.listdir(dir):
			fname = os.path.join(dir, name)
			df = gnomedesktop.item_new_from_file(fname, 0)
			print "Launching %s" % (fname,)
			df.launch([])			
		break
sys.exit(0)
