#!/usr/bin/env python
import os,sys,subprocess,shutil

import pyonlinedesktop
from pyonlinedesktop.iterdird import iterdir_d

os.environ['OD_SESSION'] = "1"

# Configure GConf, in a very hackish way
subprocess.call(['gconftool-2', '--shutdown'])
os.environ['ONLINE_DESKTOP_GCONF'] = '/usr/share/online-desktop/gconf.path'

# do pre-configuration
for fpath in iterdir_d('online-desktop/presession'):
  if os.access(fpath, os.X_OK):
    subprocess.call([fpath], stdout=sys.stdout, stderr=sys.stderr)

os.execvp('gnome-session', ['gnome-session'])
sys.exit(1)
